### PR TITLE
Minor precision

### PR DESCRIPTION
**Pull request by cccs-mog**

### CODE REVIEW

**Review by cccs-kevin — APPROVED** [review]

**Comment by cccs-sgaron** [comment]
Isnt the default 100MB not 500MB?

**Comment by cccs-rs** [comment]
Confirmed: https://cybercentrecanada.github.io/assemblyline4_docs/odm/models/config/#submission

Stock settings for Assemblyline's `submission.max_file_size` is 104857600B or 100MB.

**Review by cccs-rs — CHANGES_REQUESTED** [review]
Admonition content isn't reflective of the true default settings found in:
https://cybercentrecanada.github.io/assemblyline4_docs/odm/models/config/#submission

**Comment by cccs-mog** [comment]
Error was corrected. If there is anything let me know.

**Review by cccs-rs — APPROVED** [review]

**Pull request merged**
